# -*- coding: utf-8 -*-
"""MLOM_Lab04B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qEiNOWYtUjPheg7vrAsOqN97xEulpqet
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
import tensorflow as tf
from tensorflow import keras

data = pd.read_csv("Boston.csv")
X = data.iloc[:, :12].values
y = data.iloc[:, 12].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

reg_model = keras.Sequential([
  keras.layers.Input(shape=(X_train.shape[1],)),
  keras.layers.Dense(3, activation=None),
  keras.layers.Dense(2, activation=None),
  keras.layers.Dense(1, activation=None)
])

reg_model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.01),
                loss="mse",
                metrics=[keras.metrics.RootMeanSquaredError()])

reg_history = reg_model.fit(
  X_train, y_train,
  epochs=300,
  batch_size=32,
  validation_split=0.2,
  verbose=1
)

rmse = reg_model.evaluate(X_test, y_test, verbose=1)[1]
print(f"Test RMSE: {rmse}")

y_pred = reg_model.predict(X_test).ravel()
print(np.sqrt(mean_squared_error(y_test, y_pred)))

